version: "3.7"

services:
  frontend:
    build: .
    container_name: date222-frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
